export enum UserError {
  ERROR_EXISTED_USER = 'ERROR_EXISTED_USER',
  ERROR_USER_NOT_EXISTTING = 'ERROR_USER_NOT_EXISTTING',
  ERROR_PASSWORD_FAIL = 'ERROR_PASSWORD_FAIL',
  ERROR_ONE_OR_MORE_USER_NOT_FOUND = 'ERROR_ONE_OR_MORE_USER_NOT_FOUND',
}
